Add MIDS music format playback support
coelckers/ZMusic pull request #11
Opened 2020-09-13 18:52 UTC by Cacodemon345

https://forum.zdoom.org/viewtopic.php?f=15&t=69787

2020-09-13 19:40 UTC, alexey-lysiuk requested changes

2020-09-13 19:40 UTC, alexey-lysiuk commented on include/zmusic.h
> +	MIDI_MIDS
Please add colon at the end of new line, so we don’t need to change it next time when another format is added.

2020-09-13 19:40 UTC, alexey-lysiuk commented on source/midisources/midisource_mids.cpp
> +        std::vector<uint32_t> midiMessageData;
What’s the point of intermediate buffer `midiMessageData`? Why don’t you insert it directly to `midiBuffer`?

2020-09-13 19:40 UTC, alexey-lysiuk commented on source/midisources/midisource.h
> +	std::vector<uint32_t> midiBuffer;
Please name members uniformly, i.e. `MidiBuffer`, to match other members from this and related classes.

2020-09-13 19:40 UTC, alexey-lysiuk commented on source/midisources/midisource.h
> +	size_t MidsP, MaxMidsP;
What does `P` mean in these names? Position? Pointer? Place?
Please rename them so we don’t need to guess that.

2020-09-13 19:40 UTC, alexey-lysiuk commented on source/midisources/midisource_mids.cpp
> +** Code to let ZDoom play MIDS MIDI music through the MIDI streaming API.
This project is not ZDoom anymore.

2020-09-13 19:40 UTC, alexey-lysiuk commented on source/midisources/midisource_mids.cpp
> +    if (data[12] != 'f' || data[13] != 'm' || data[14] != 't' || data[15] != ' ')
Please add validation of input data size throughout whole this function.

2020-09-13 19:40 UTC, alexey-lysiuk commented on source/midisources/midisource_mids.cpp
> +}
Please add empty line at the end of the file.

2020-09-13 19:40 UTC, alexey-lysiuk commented on source/midisources/midisource_mids.cpp
> +        if (MidsP >= MaxMidsP) goto end;
Please replace `goto` with `break`.

2020-09-13 19:40 UTC, alexey-lysiuk commented on source/midisources/midisource_mids.cpp
> +        events += 3;
Is it possible to read beyond `midiBuffer` here?

2020-09-14 06:06 UTC, Cacodemon345 commented on include/zmusic.h
> +	MIDI_MIDS
I didn't add a comma for consistency.

2020-09-14 06:08 UTC, Cacodemon345 commented on source/midisources/midisource_mids.cpp
> +        std::vector<uint32_t> midiMessageData;
It was easier to read the data into the intermediate vector array and then insert it into the base midiBuffer vector array.

2020-09-14 06:09 UTC, Cacodemon345 commented on source/midisources/midisource.h
> +	size_t MidsP, MaxMidsP;
That MidsP and MaxMidsP part was taken from the MUS code.

2020-09-14 06:09 UTC, Cacodemon345 commented on source/midisources/midisource_mids.cpp
> +** Code to let ZDoom play MIDS MIDI music through the MIDI streaming API.
Yeah, that was a oversight.

2020-09-14 06:13 UTC, Cacodemon345 commented on source/midisources/midisource_mids.cpp
> +        events += 3;
It should not be possible.

2020-09-14 06:27 UTC, alexey-lysiuk commented on include/zmusic.h
> +	MIDI_MIDS
For consistency with what? It’s bad practice to skip comma after the last enumeration entry if it doesn’t have a special meaning like count or max value.

2020-09-14 06:34 UTC, alexey-lysiuk commented on source/midisources/midisource_mids.cpp
> +        std::vector<uint32_t> midiMessageData;
Sorry to be blunt, but in my opinion, it’s much easier to do not merge such code than to deal with it later.

2020-09-14 06:40 UTC, alexey-lysiuk commented on source/midisources/midisource_mids.cpp
> +        events += 3;
In the loop breaking condition, `MidsP >= MaxMidsP`, there is no point to use greater-or-equal if you 100% sure that the current index never exceeds max one. If not, it needs to be tested before reading any data.

2020-09-14 06:41 UTC, coelckers commented on include/zmusic.h
> +	MIDI_MIDS
Well, the enum previously didn't have it either, so where's the problem?

2020-09-14 06:41 UTC, coelckers commented on source/midisources/midisource_mids.cpp
> +        std::vector<uint32_t> midiMessageData;
Well, the old enum didn't have it either, so where's the problem?

2020-09-14 06:44 UTC, coelckers commented on source/midisources/midisource.h
> +	size_t MidsP, MaxMidsP;
Does it really matter? If we took it to that, we'd have to change half the code.

2020-09-14 06:46 UTC, alexey-lysiuk commented on include/zmusic.h
> +	MIDI_MIDS
There will be only one line change if a new entry will be added later.

2020-09-14 06:48 UTC, coelckers commented on source/midisources/midisource_mids.cpp
> +        std::vector<uint32_t> midiMessageData;
This needs to change before it gets added. This may look trivial but performs a full memory allocation each time for zero gain.

2020-09-14 06:49 UTC, coelckers commented on source/midisources/midisource_mids.cpp
> +}
Agreed on this one. This goto is totally unnecessary and should be replaced with proper control statements.

2020-09-14 06:50 UTC, coelckers commented on source/midisources/midisource_mids.cpp
> +        if (MidsP >= MaxMidsP) goto end;
Agreed on this one. This goto is totally unnecessary and should be replaced with proper control statements.

2020-09-14 06:51 UTC, coelckers commented on source/midisources/midisource_mids.cpp
> +        events += 3;
"Should" is not good enough. Can you give a guarantee that no malformed files go through here?

2020-09-14 06:52 UTC, coelckers reviewed
Overall I approve with this PR, but please fix those minor issues first

2020-09-14 09:04 UTC, Cacodemon345 commented on source/midisources/midisource_mids.cpp
> +        events += 3;
Well, when reaching at the end of track, the MidsP will be equal to MaxMidsP, which means the end of track.

2020-09-14 09:15 UTC, alexey-lysiuk commented on source/midisources/midisource_mids.cpp
> +        events += 3;
There can be only one element left in `midiBuffer`, or just two elements. This code assumes that there are at least three elements available when loop iteration is started. However, I see no validation of this assumption.

2020-09-14 09:20 UTC, Cacodemon345 commented on source/midisources/midisource_mids.cpp
> +        events += 3;
After some testing, I can confirm that the greater-or-equal check is needed, because the application will crash otherwise.

2020-09-14 10:49 UTC, coelckers commented
Looks much better, but the last two issues I cannot verify online so they'll have to wait.

2020-09-15 06:35 UTC, Cacodemon345 commented
Any further issues to check?

2020-09-15 06:41 UTC, coelckers commented
No, it just needs to be tested once. I didn't manage yesterday evening.

2020-09-27 11:17 UTC, coelckers commented
Merged manually.

2020-09-27 11:17 UTC, closed without merging